### ISSUE TITLE
No version of 'react-native-dom' found that satisfies a peer dependency on 'react-native@0.56.0'

### ISSUE THREAD

**Issue by DevKiri** [vincentriemer/react-native-dom#62]
When use "$: react-native dom"
Appears: 
No version of 'react-native-dom' found that satisfies a peer dependency on 'react-native@0.56.0'

This is my package.json:

{
  "name": "dom",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-dom": "^16.4.1",
    "react-native": "0.56.0",
    "react-native-dom": "0.2.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "^5",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1",
    "rnpm-plugin-dom": "^0.1.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by vincentriemer** [comment]
Ah, that's because RND doesn't currently support RN 0.56 (I'm working really hard on it), so in the meantime you're going to have to downgrade to 0.55. 

This could also be an opportunity for anyone who's interested in contributing to improve that error message!

**Comment by sallespro** [comment]
i couldn't get started with 

```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-dom": "0.2.0",
    "rnpm-plugin-dom": "^0.1.1"
```

```
error: bundling failed: Error: Cannot find module 'AccessibilityInfo' (While processing preset: "/Users/rrocsal/dev/code/research/dom/node_modules/react-native/Libraries/react-native/react-native-implementation.js")
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by darrencruse** [comment]
JIC it helps somebody I was attempting to do a little hello world following the Getting Started steps in the README but downgrading react to 0.55 as stated above...

But me I was getting a different error from the bundler (Plugin 0 provided an invalid property of "default").

Googling I found that error mentioned here:
https://github.com/storybooks/storybook/issues/3897

Following the final tip given there did get it working for me i.e. my package.json looks like:
```
{
  "name": "RNDTest1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.55.0",
    "react-native-dom": "0.2.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "2.1.0",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1",
    "rnpm-plugin-dom": "^0.1.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by luandro** [comment]
Should be added to the README that react-native v0.56 isn't supported.
