### ISSUE TITLE
How to install react-native-vector-icon

### ISSUE THREAD

**Issue by mrtry** [vincentriemer/react-native-dom#90]
I want to use `react-native-vector-icon`.
Tried install, Got the following error.

What is `domDependencyConfig.json` ...? 

```
$ yarn add react-native-vector
$ react-native link react-native-vector-icons
rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?

Could not find domDependencyConfig.json in your project, please add it.

Error: Could not find domDependencyConfig.json in your project, please add it.
    at findDependencyConfigPath (/Users/symmt/Program/Study/ReactNative/ReactNativeDomIntoReactNativePaper/node_modules/react-native-dom/local-cli/core/dom/findDepConfigPath.js:22:11)
    at Object.projectConfigDom [as projectConfig] (/Users/symmt/Program/Study/ReactNative/ReactNativeDomIntoReactNativePaper/node_modules/react-native-dom/local-cli/core/dom/index.js:9:33)
    at Object.keys.forEach.key (/Users/symmt/Program/Study/ReactNative/ReactNativeDomIntoReactNativePaper/node_modules/react-native/local-cli/core/index.js:100:36)
    at Array.forEach (<anonymous>)
    at Object.getProjectConfig (/Users/symmt/Program/Study/ReactNative/ReactNativeDomIntoReactNativePaper/node_modules/react-native/local-cli/core/index.js:99:28)
    at Object.link [as func] (/Users/symmt/Program/Study/ReactNative/ReactNativeDomIntoReactNativePaper/node_modules/react-native/local-cli/link/link.js:121:22)
    at Promise.resolve.then (/Users/symmt/Program/Study/ReactNative/ReactNativeDomIntoReactNativePaper/node_modules/react-native/local-cli/cliEntry.js:117:22)
    at <anonymous>
```

**Comment by anhdle14** [comment]
Experienced this too, are there any hacks or solutions yet?

**Comment by iamralpht** [comment]
I did `touch domDependencyConfig.json` and the error went away. YMMV.

**Comment by anhdle14** [comment]
That really not fix the issue, because react-native-dom still depends on native-module to be ported to the web.
For the future, we need to somehow do:
1. `react-native link` to generate dependencies for the web. 
2. `react-native-web` to somehow take react-native link to use the web-version instead of native module.

**Comment by iamralpht** [comment]
Isn't the list of "native modules" in `dom/bootstrap.js` equivalent to what `react-native link` does for the iOS and Android build systems?

**Comment by anhdle14** [comment]
Haven't got the chance to look into the issue but in short: yes
```javascript
import { RNDomInstance } from "react-native-dom";
import { name as appName } from "../app.json";

// Path to RN Bundle Entrypoint ================================================
const rnBundlePath = "./entry.bundle?platform=dom&dev=true";

// React Native DOM Runtime Options =============================================
const ReactNativeDomOptions = {
  enableHotReload: false,
  nativeModules: []
};

// App Initialization ============================================================
const app = new RNDomInstance(
  rnBundlePath,
  appName,
  document.body,
  ReactNativeDomOptions
);

app.start();
```
